services:
  backend:
    ports:
      - "3000:3000"
    build:
      ./backend
    command: sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    volumes:
      - type: bind
        source: ./backend
        target: /app

  frontend:
    ports:
      - "3001:3000"
    build: 
      ./frontend
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - type: bind
        source: ./frontend
        target: /src

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=yokota
      - MYSQL_DATABASE=shelf_app
    ports:
      - "3306:3306"
    
    volumes:
      - type: volume
        source: db-compose-volume
        target: /var/lib/mysql

    image: mysql:8.2.0
        

    

volumes:
  db-compose-volume:
    

